#Server
server.port=8080

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/pet_adoption_main_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework=INFO
logging.level.com.petadoption=DEBUG

# Feign client target (medical-svc)
medical.service.url=http://localhost:8090